# Generated by Django 4.0.3 on 2022-04-09 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'db_table': 'categories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('address', models.CharField(max_length=255, verbose_name='Manzili')),
            ],
            options={
                'verbose_name': 'Ishlab chiqaruvchi',
                'verbose_name_plural': 'Ishlab chiqaruvchilar',
                'db_table': 'manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('image', models.ImageField(upload_to='img', verbose_name='Rasm')),
                ('description', models.TextField(null=True, verbose_name='Tafsilotlar')),
                ('price', models.PositiveIntegerField(verbose_name='Narxi')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.manufacturer', verbose_name='Ishlab chiqaruvchi')),
            ],
            options={
                'verbose_name': 'Maxsulot',
                'verbose_name_plural': 'Maxsulotlar',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Diagonal')),
                ('display_type', models.CharField(max_length=255, verbose_name='Displey turi')),
                ('processor_freq', models.CharField(max_length=255, verbose_name='Chastotasi')),
                ('ram', models.CharField(max_length=255, verbose_name='Tezkor xotira')),
                ('rom', models.CharField(max_length=255, null=True, verbose_name='Asosiy xotira')),
                ('videokart', models.CharField(max_length=255, verbose_name='Videokarta')),
                ('time_without_charge', models.CharField(max_length=255, verbose_name='Akkumulyator ishlash vaqti')),
            ],
            options={
                'verbose_name': 'Noutbuk',
                'verbose_name_plural': 'Noutbuklar',
                'db_table': 'notebooks',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Planshet',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Diagonal')),
                ('display_type', models.CharField(max_length=255, verbose_name='Displey turi')),
                ('resolution', models.CharField(max_length=255, verbose_name="Ekran o'lchamlari")),
                ('accum_volume', models.CharField(max_length=255, verbose_name='Akkumulyator hajmi')),
                ('ram', models.CharField(max_length=255, verbose_name='Tezkor xotira')),
                ('rom', models.CharField(max_length=255, null=True, verbose_name='Asosiy xotira')),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='Asosiy kamera')),
                ('front_cam_mp', models.CharField(max_length=255, verbose_name='Frontal kamera')),
            ],
            options={
                'verbose_name': 'Planshet',
                'verbose_name_plural': 'Planshetlar',
                'db_table': 'planshets',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Diagonal')),
                ('display_type', models.CharField(max_length=255, verbose_name='Displey turi')),
                ('resolution', models.CharField(max_length=255, verbose_name="Ekran o'lchamlari")),
                ('accum_volume', models.CharField(max_length=255, verbose_name='Akkumulyator hajmi')),
                ('ram', models.CharField(max_length=255, verbose_name='Tezkor xotira')),
                ('rom', models.CharField(max_length=255, null=True, verbose_name='Asosiy xotira')),
                ('count_main_cam', models.PositiveIntegerField(verbose_name='Asosiy kameralar soni')),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='Asosiy kamera')),
                ('front_cam_mp', models.CharField(max_length=255, verbose_name='Frontal kamera')),
            ],
            options={
                'verbose_name': 'Smartfon',
                'verbose_name_plural': 'Smartfonlar',
                'db_table': 'smartphones',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='TV_product',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('diagonal', models.CharField(max_length=50, verbose_name='Diagonal')),
                ('display_type', models.CharField(max_length=50, verbose_name='Displey turi')),
                ('tv_type', models.CharField(max_length=50, verbose_name='Televizor turi')),
                ('wifi', models.BooleanField(default=False, verbose_name='Wifi mavjudligi')),
                ('on_smart', models.BooleanField(default=False, verbose_name='Smart TV')),
                ('on_stereo', models.BooleanField(default=False, verbose_name='Stereo ovoz')),
                ('created_year', models.CharField(choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=10, verbose_name='Ishlab chiqarilgan yili')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Subkategoriya',
                'verbose_name_plural': 'Subkategoriyalar',
                'db_table': 'subcategories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.subcategory', verbose_name='Subkategoriya'),
        ),
    ]
