# Generated by Django 4.0.3 on 2022-04-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='rasm.jpg', upload_to='', verbose_name='Rasmi'),
            preserve_default=False,
        ),
    ]
